import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const source = process.env.OPENAPI_URL || "http://localhost:8000/openapi.json";
const output = fileURLToPath(
  new URL("../src/api/generated/schema.d.ts", import.meta.url),
);

const schemaSource = source.startsWith("http://") || source.startsWith("https://")
  ? new URL(source)
  : source;
const nodes = await openapiTS(schemaSource, { alphabetize: true });
const header = [
  "/**",
  " * AUTO-GENERATED by openapi-typescript. Do not edit manually.",
  ` * Source: ${source}`,
  " */",
  "",
].join("\n");

await writeFile(output, `${header}${astToString(nodes)}`, "utf8");
console.log(`OpenAPI types generated: ${output}`);
